In [1]:
import numpy as np

In [3]:
a = np.arange(10, 71, 10)
b = np.arange(1, 8, 1)
a, b

(array([10, 20, 30, 40, 50, 60, 70]), array([1, 2, 3, 4, 5, 6, 7]))

In [4]:
a+b

array([11, 22, 33, 44, 55, 66, 77])

In [5]:
a-b

array([ 9, 18, 27, 36, 45, 54, 63])

In [6]:
a*b

array([ 10,  40,  90, 160, 250, 360, 490])

In [7]:
a+5

array([15, 25, 35, 45, 55, 65, 75])

In [8]:
b**2

array([ 1,  4,  9, 16, 25, 36, 49], dtype=int32)

In [10]:
a *= 2
a

array([ 20,  40,  60,  80, 100, 120, 140])

In [13]:
a = a /3 #a /= 3

In [14]:
a

array([ 6.66666667, 13.33333333, 20.        , 26.66666667, 33.33333333,
       40.        , 46.66666667])

In [15]:
a.dtype

dtype('float64')

In [16]:
arr1 = np.array([ [1],[2],[3]  ])
arr1

array([[1],
       [2],
       [3]])

In [17]:
arr2 = np.array([ [1,2,3] ])
arr2

array([[1, 2, 3]])

In [18]:
arr1 + arr2

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [19]:
arr1 * arr2

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

### Wybieranie danych z tablicy

In [20]:
np.random.seed(0)
arr = np.random.randint(-10, 11, (7,8) )
arr

array([[  2,   5, -10,  -7,  -7,  -3,  -1,   9],
       [  8,  -6,  -4,   2,  -9,  -4,  -3,   4],
       [  7,  -5,   3,  -2,  -1,  10,   9,   6],
       [  9,  -5,   5,   5, -10,   8,  -7,   7],
       [  9,   9,   9,   4,  -3, -10,  -9,  -1],
       [-10,   0,  10,  -7,   1,   8,  -8, -10],
       [-10,  -6,  -5,  -4,  -2,  10,   7,   5]])

In [21]:
# ostatni wiersz
arr[6], arr[-1]

(array([-10,  -6,  -5,  -4,  -2,  10,   7,   5]),
 array([-10,  -6,  -5,  -4,  -2,  10,   7,   5]))

In [25]:
# wiersz 2 i 3, co 3-cia kolumna
arr[ 1:3 , ::3 ]

array([[ 8,  2, -3],
       [ 7, -2,  9]])

In [26]:
# tylko wiersz pierwszy i ostatni
arr[ [0,-1] ]

array([[  2,   5, -10,  -7,  -7,  -3,  -1,   9],
       [-10,  -6,  -5,  -4,  -2,  10,   7,   5]])

In [28]:
arr[ [-1,0] ]

array([[-10,  -6,  -5,  -4,  -2,  10,   7,   5],
       [  2,   5, -10,  -7,  -7,  -3,  -1,   9]])

In [29]:
arr

array([[  2,   5, -10,  -7,  -7,  -3,  -1,   9],
       [  8,  -6,  -4,   2,  -9,  -4,  -3,   4],
       [  7,  -5,   3,  -2,  -1,  10,   9,   6],
       [  9,  -5,   5,   5, -10,   8,  -7,   7],
       [  9,   9,   9,   4,  -3, -10,  -9,  -1],
       [-10,   0,  10,  -7,   1,   8,  -8, -10],
       [-10,  -6,  -5,  -4,  -2,  10,   7,   5]])

In [34]:
# ostatnia kolumna
arr[ :, [-1] ]

array([[  9],
       [  4],
       [  6],
       [  7],
       [ -1],
       [-10],
       [  5]])

In [36]:
arr.transpose()[-1]

array([  9,   4,   6,   7,  -1, -10,   5])

In [38]:
arr.T[-1]

array([  9,   4,   6,   7,  -1, -10,   5])

In [39]:
arr

array([[  2,   5, -10,  -7,  -7,  -3,  -1,   9],
       [  8,  -6,  -4,   2,  -9,  -4,  -3,   4],
       [  7,  -5,   3,  -2,  -1,  10,   9,   6],
       [  9,  -5,   5,   5, -10,   8,  -7,   7],
       [  9,   9,   9,   4,  -3, -10,  -9,  -1],
       [-10,   0,  10,  -7,   1,   8,  -8, -10],
       [-10,  -6,  -5,  -4,  -2,  10,   7,   5]])

In [40]:
for row in arr:
    print(row)
    print("="*50)

[  2   5 -10  -7  -7  -3  -1   9]
[ 8 -6 -4  2 -9 -4 -3  4]
[ 7 -5  3 -2 -1 10  9  6]
[  9  -5   5   5 -10   8  -7   7]
[  9   9   9   4  -3 -10  -9  -1]
[-10   0  10  -7   1   8  -8 -10]
[-10  -6  -5  -4  -2  10   7   5]


### Porównania szybkości Numpy vs Python list

In [42]:
%%timeit -r 20 -n 500
[x**2 for x in range(1,1001)]

718 µs ± 72.2 µs per loop (mean ± std. dev. of 20 runs, 500 loops each)


In [43]:
%%timeit -r 20 -n 500
np.arange(1,1001)**2

11 µs ± 2.73 µs per loop (mean ± std. dev. of 20 runs, 500 loops each)


In [44]:
718/11

65.27272727272727