In [7]:
import numpy as np

In [8]:
# klasycznie
numbers_list = [-20, -1, 10, 50, -100, 100, -512, 123, 432, 111, -1024]
[x for x in numbers_list if x>0]

[10, 50, 100, 123, 432, 111]

In [9]:
arr = np.array(numbers_list)
arr

array([  -20,    -1,    10,    50,  -100,   100,  -512,   123,   432,
         111, -1024])

In [10]:
arr>0

array([False, False,  True,  True, False,  True, False,  True,  True,
        True, False])

In [11]:
arr[ arr>0 ]

array([ 10,  50, 100, 123, 432, 111])

In [12]:
arr[ arr%2==0  ]

array([  -20,    10,    50,  -100,   100,  -512,   432, -1024])

In [15]:
# pokaz tylko >0 i jednoczesnie <=100
arr[ (arr>0)&(arr<=100) ]

array([ 10,  50, 100])

In [17]:
# pokaz tylko <0 lub >100
arr[ (arr<0)|(arr>100) ]

array([  -20,    -1,  -100,  -512,   123,   432,   111, -1024])

In [18]:
# tablica z NaN
arr = np.array([-1, 4, 10, np.NaN, 15, 20, np.NaN])
arr

array([-1.,  4., 10., nan, 15., 20., nan])

In [20]:
arr.dtype

dtype('float64')

In [21]:
np.isnan(arr)

array([False, False, False,  True, False, False,  True])

In [23]:
arr[ ~np.isnan(arr) ] # tylda = negacja

array([-1.,  4., 10., 15., 20.])

In [24]:
arr

array([-1.,  4., 10., nan, 15., 20., nan])

In [27]:
arr = arr[ ~np.isnan(arr) ]
np.mean(arr), np.median(arr), np.std(arr), np.min(arr), np.max(arr)

(9.6, 10.0, 7.49933330370107, -1.0, 20.0)