In [23]:
import numpy as np

In [24]:
class Perceptron:
    
    def __init__(self):
        """ Inicjalizacja wag dla perceptronu """
        np.random.seed(0)
        self.weights = 4 * np.random.random((3,1)) - 2
        
    
    def sigmoid(self, x):
        """ Funkcja aktywacji """
        return 1/(1+np.exp(-x))
    
    def d_sigmoid(self, x):
        """ Pochodna do f. aktywacji """
        return x*(1-x)
        
    def propagation(self, inputs):
        """ Propagacja danych i wag """
        return self.sigmoid( np.dot(inputs.astype("float"), self.weights) )
    
    def back_propagation(self, propagation_result, train_input, train_output):
        """ Prosty algorytm prop. wstecznej """
        error = train_output - propagation_result
        self.weights += np.dot( train_input.T, error*self.d_sigmoid(propagation_result) )
    
    def train(self, train_input, train_output, epochs):
        for _ in range(epochs):
            prop_result = self.propagation(train_input)
            self.back_propagation(prop_result, train_input, train_output)    

In [25]:
model = Perceptron()

X = np.array([
    [1,1,0], [1,1,1], [1,1,0], [1,0,0], [0,1,1], [0,1,0]
])

y = np.array([[0, 1, 0, 0, 1, 0]]).T

In [26]:
print(model.weights)
model.train(X, y, 50_000)
print(model.weights)

[[0.19525402]
 [0.86075747]
 [0.4110535 ]]
[[-5.04497798]
 [-5.04495648]
 [15.28006533]]


In [27]:
X_test = np.array([
    [1,1,1], [0,0,1], [1,0,1] , [1,1,0], [0,0,1]
])

for x in X_test:
    print(f"{x} = {model.propagation(x)}")

[1 1 1] = [0.99445959]
[0 0 1] = [0.99999977]
[1 0 1] = [0.99996411]
[1 1 0] = [4.14934092e-05]
[0 0 1] = [0.99999977]
